// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDoEiDCvXgT6v3h5PdY_EUYIvNXtph7E',
    appId: '1:94086995576:web:796cdbc1f8e54d69bb578d',
    messagingSenderId: '94086995576',
    projectId: 'quizlet-63d29',
    authDomain: 'quizlet-63d29.firebaseapp.com',
    storageBucket: 'quizlet-63d29.appspot.com',
    measurementId: 'G-TNFZ4C45LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNKg9xk1yVLgaWy9t97sjjZkib6XZ07w',
    appId: '1:94086995576:android:4ab5687695b1c3a3bb578d',
    messagingSenderId: '94086995576',
    projectId: 'quizlet-63d29',
    storageBucket: 'quizlet-63d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUb1Cz8mo-Tj1_O_V9DFT8_t4AldlkUg4',
    appId: '1:94086995576:ios:05a7cc6a35f6661abb578d',
    messagingSenderId: '94086995576',
    projectId: 'quizlet-63d29',
    storageBucket: 'quizlet-63d29.appspot.com',
    androidClientId: '94086995576-qvirk32gn4mugi7cru79f5q3cfd2hk73.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCalendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUb1Cz8mo-Tj1_O_V9DFT8_t4AldlkUg4',
    appId: '1:94086995576:ios:55110cbf43cf6baabb578d',
    messagingSenderId: '94086995576',
    projectId: 'quizlet-63d29',
    storageBucket: 'quizlet-63d29.appspot.com',
    androidClientId: '94086995576-qvirk32gn4mugi7cru79f5q3cfd2hk73.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCalendarApp.RunnerTests',
  );
}
